import { useMemo, useRef, useState } from 'react';
import { zipSync, strToU8 } from 'fflate';
import { Dropzone } from './Dropzone';
import { PresetControls } from './PresetControls';
import { CompressionList } from './CompressionList';
import { PreviewPanel } from './PreviewPanel';
import { loadSettings, saveSettings } from '../../lib/utils/storage';
import type { CompressionJob, CompressionSettings, WorkerCompressResponse } from '../../lib/utils/types';

const defaultSettings: CompressionSettings = {
  format: 'webp',
  quality: 82,
  stripMetadata: true
};

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export default function CompressorApp() {
  const [settings, setSettings] = useState<CompressionSettings>(() => loadSettings() ?? defaultSettings);
  const [jobs, setJobs] = useState<CompressionJob[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [globalError, setGlobalError] = useState<string>('');
  const workerRef = useRef<Worker | null>(null);

  const selectedJob = useMemo(() => jobs.find((job) => job.id === selectedId), [jobs, selectedId]);

  function ensureWorker() {
    if (!workerRef.current) {
      workerRef.current = new Worker(new URL('../../lib/workers/compression.worker.ts', import.meta.url), { type: 'module' });
      workerRef.current.onmessage = (event: MessageEvent<WorkerCompressResponse>) => {
        setJobs((current) =>
          current.map((job) => {
            if (job.id !== event.data.id) return job;
            if (!event.data.ok) {
              return { ...job, status: 'error', error: event.data.error, progress: 100 };
            }
            return {
              ...job,
              status: 'done',
              progress: 100,
              output: event.data.output,
              outputName: event.data.outputName
            };
          })
        );
      };
    }
    return workerRef.current;
  }

  function addFiles(files: File[]) {
    const next = files
      .filter((file) => file.type.startsWith('image/'))
      .map((file) => ({
        id: crypto.randomUUID(),
        file,
        status: 'queued' as const,
        progress: 0
      }));

    if (!next.length) {
      setGlobalError('Please select image files only.');
      return;
    }

    setGlobalError('');
    setJobs((current) => {
      const combined = [...current, ...next];
      if (!selectedId && combined[0]) setSelectedId(combined[0].id);
      return combined;
    });
  }

  function runCompression() {
    if (!jobs.length) {
      setGlobalError('Add at least one image before compressing.');
      return;
    }

    setGlobalError('');
    saveSettings(settings);
    const worker = ensureWorker();

    setJobs((current) =>
      current.map((job) => {
        worker.postMessage({ id: job.id, file: job.file, settings });
        return { ...job, status: 'processing', progress: 20, error: undefined };
      })
    );
  }

  async function downloadAllZip() {
    const completed = jobs.filter((job) => job.output && job.outputName);
    if (!completed.length) {
      setGlobalError('Compress files first to download a zip.');
      return;
    }

    const archive: Record<string, Uint8Array> = {
      'README.txt': strToU8('Generated by PixelPress. Compression happened entirely in your browser.')
    };

    for (const job of completed) {
      archive[job.outputName!] = new Uint8Array(await job.output!.arrayBuffer());
    }

    const zip = zipSync(archive, { level: 6 });
    const zipBytes = new Uint8Array(zip);
    downloadBlob(new Blob([zipBytes], { type: 'application/zip' }), 'pixelpress-compressed.zip');
  }

  return (
    <div className="space-y-6">
      <div className="space-y-2">
        <h1 className="text-4xl font-bold text-white">Image Compressor App</h1>
        <p className="text-slate-300">All processing stays local in your browser. No uploads, no backend queues.</p>
      </div>

      <Dropzone onFiles={addFiles} />
      <PresetControls settings={settings} onChange={setSettings} />

      <div className="flex flex-wrap gap-3">
        <button type="button" onClick={runCompression} className="rounded-lg bg-cyan-400 px-4 py-2 font-semibold text-slate-900">Compress Batch</button>
        <button type="button" onClick={downloadAllZip} className="rounded-lg border border-white/20 px-4 py-2 font-semibold text-white">Download All (.zip)</button>
        {selectedJob?.output && selectedJob.outputName ? (
          <button
            type="button"
            onClick={() => downloadBlob(selectedJob.output!, selectedJob.outputName!)}
            className="rounded-lg border border-white/20 px-4 py-2 font-semibold text-white"
          >
            Download Selected
          </button>
        ) : null}
      </div>

      {globalError ? <p className="rounded-lg border border-rose-400/40 bg-rose-500/10 p-3 text-sm text-rose-200">{globalError}</p> : null}

      <div className="grid gap-5 xl:grid-cols-[360px_1fr]">
        <CompressionList jobs={jobs} selectedId={selectedId} onSelect={setSelectedId} />
        <PreviewPanel job={selectedJob} />
      </div>
    </div>
  );
}
